# config.yaml for CHAZ parser

# Location of netCDF files in ssp245, ssp585 sub-directories
raw_data_dir: "/mnt/cluster/mistral/incoming_data/lee-2022-CHAZ-global-TC-tracks"
# When subsetting for baseline or future scenarios, take this many years either side
epoch_half_width_years: 15

