# to install this environment:
# micromamba create -f environment.yml -y
name: chaz
channels:
  - conda-forge  # majority of dependencies
  - nodefaults
dependencies:
  - python=3.12
  - pip:
    - -e .
  - geopandas
  - hatch
  - jupyter
  - netCDF4
  - notebook
  - numpy
  - matplotlib
  - bioconda::snakemake
  - seaborn
  - tqdm
  - xarray
